title: Data Scientist and AI Notebook
author: Cheng-Lin Li
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  This is my Blog for Data Scientist Notebook which includes Artificial Intelligence, Machine Learning, Natural Language Processing, Knowledge Graphs, Information Visualization, and Data Mining.

# social links
# twitter_username: jekyllrb
github_username:  Cheng-Lin-Li
# rss: rss
# dribbble_username: jekyll
facebook_username: clark.cl.li
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: chenglin-li
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:
  shortname: cheng-lin-li

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-116280074-1

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- Github
- project.html
- about.html


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
